### ISSUE TITLE
服务器name中地区（HK、GB等）字符串编码/格式的问题

### ISSUE THREAD

**Issue by zhechenzhu** [youfou/dlercloud#1]
感谢开发API工具。我在使用过程中有一个问题，应该与您的开发的工具无关，但想请教一下。

在通过API调取服务器信息后，服务器属性name（如“HK 香港 IPLC 01”）中的地区字符串（“HK”）无法通过 `“HK” in v2node.name` 识别出来。同样的情况下面如果判断的是线路（如"IPLC"）则没有问题。

仔细观察vscode终端print输出发现name中的地区字符串字体要比线路字符串小一点 （如 “🇭🇰 香港 IPLC 01”）。请问怎样实现对该类字符串的识别？

开发环境是vscode + remote ssh + linux server。谢谢！

**Comment by youfou** [comment]
“🇨🇳”、“🇭🇰” 等都是 emoji 符号，而且地区旗帜类的 emoji 都由两个符号组成。你在开发环境中看到的 字体与常规有差异的 “H K” 字符，实际是因为当前环境不支持这种多个符号组成的 emoji，所以显示成了两个符号。
我没有使用 vscode，不过在我所使用的 PyCharm (Mac) 中也有相同的问题。
如果为了筛选节点，建议直接采用其他普通字符，例如 “香港”。

**Comment by zhechenzhu** [comment]
谢谢！学习了。用中文地区名没问题。
